### ISSUE TITLE
ID list for idividual training

### ISSUE THREAD

**Issue by wush978** [11thDeepLearningGroup2015/MLDS_HW1#7]
We should divide the training dataset into:

1. training data set 80%
2. ensemble data set 10%
3. validation data set 10%

How do you think?

**Comment by wush978** [comment]
另外這樣的切割不知道要不要多切幾組

**Comment by ccwang002** [comment]
可以切一組，大家都不能看 2, 3。切多組可能就不準備，晚一點再做吧

**Comment by wush978** [comment]
75b5e184180ef4fd9d21f9fe2433e32accd8ab36
